project 'AnyGIS_filegenerator.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnyGIS_filegenerator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnyGIS_filegenerator
  
  # pod 'GRDB.swift'
  pod 'SQLite.swift'
end
